[package]
name = "Information_Transformation_Algorithms_Task04"
version = "0.4.5"
edition = "2024"

[dependencies]
zwl_gs = {path = "zwl"}
#CLI!
clap = { version = "4.5.48", features = ["derive"] }
dialoguer = "0.12.0"
serde = { version = "1.0.226", features = ["derive"] }
